name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2 
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  #image_path_android: "assets/android/icon.png"
  #image_path_ios: "assets/ios/icon.png"


flutter:
  uses-material-design: true
